services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: langgraph
    ports: ["5432:5432"]

  ai-server:
    image: ai-server
    depends_on: [db]
    ports: ["8123:8000"]
    environment:
      DATABASE_URI: postgresql://app:secret@db:5432/langgraph
      REDIS_URI: redis://192.168.30.100:6379/0
      LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
      LANGSMITH_TRACING: "true"
      LANGSMITH_PROJECT: "ai-server"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
